FROM registry.ci.openshift.org/open-cluster-management/builder:nodejs14-linux as builder

# Root needed for yum update, gets reset to 1001 below.
USER root
WORKDIR /opt/app-root/src/application-ui
COPY . /opt/app-root/src/application-ui/
RUN yum install git -y
RUN yum --nobest -y update
RUN cd /opt/app-root/src/application-ui/ && npm ci && npm run build:production
RUN ls /opt/app-root/src/application-ui

ENV BABEL_DISABLE_CACHE=1 \
    NODE_ENV=production \
    USER_UID=1001

EXPOSE 3000

USER ${USER_UID}
CMD ["node", "app.js"]
